/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ActorObject,
    ActorObjectFromJSON,
    ActorObjectFromJSONTyped,
    ActorObjectToJSON,
} from './';

/**
 * Actor response object.
 * @export
 * @interface ActorResponse
 */
export interface ActorResponse {
    /**
     * 
     * @type {ActorObject}
     * @memberof ActorResponse
     */
    data: ActorObject;
}

export function ActorResponseFromJSON(json: any): ActorResponse {
    return ActorResponseFromJSONTyped(json, false);
}

export function ActorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ActorObjectFromJSON(json['data']),
    };
}

export function ActorResponseToJSON(value?: ActorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ActorObjectToJSON(value.data),
    };
}


