/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MaritalStatuses,
    MaritalStatusesFromJSON,
    MaritalStatusesFromJSONTyped,
    MaritalStatusesToJSON,
} from './';

/**
 * Actor request object for update.
 * @export
 * @interface ActorUpdateRequest
 */
export interface ActorUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof ActorUpdateRequest
     */
    documentId?: number;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    lastName?: string;
    /**
     * 
     * @type {MaritalStatuses}
     * @memberof ActorUpdateRequest
     */
    maritalStatus?: MaritalStatuses;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    houseNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    postcode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ActorUpdateRequest
     */
    liveTogether?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateRequest
     */
    personalRelation?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof ActorUpdateRequest
     */
    guardians?: Array<number>;
}

export function ActorUpdateRequestFromJSON(json: any): ActorUpdateRequest {
    return ActorUpdateRequestFromJSONTyped(json, false);
}

export function ActorUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActorUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': !exists(json, 'document_id') ? undefined : json['document_id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'maritalStatus': !exists(json, 'marital_status') ? undefined : MaritalStatusesFromJSON(json['marital_status']),
        'dateOfBirth': !exists(json, 'date_of_birth') ? undefined : json['date_of_birth'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'houseNumber': !exists(json, 'house_number') ? undefined : json['house_number'],
        'street': !exists(json, 'street') ? undefined : json['street'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'postcode': !exists(json, 'postcode') ? undefined : json['postcode'],
        'liveTogether': !exists(json, 'live_together') ? undefined : json['live_together'],
        'personalRelation': !exists(json, 'personal_relation') ? undefined : json['personal_relation'],
        'guardians': !exists(json, 'guardians') ? undefined : json['guardians'],
    };
}

export function ActorUpdateRequestToJSON(value?: ActorUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'document_id': value.documentId,
        'title': value.title,
        'first_name': value.firstName,
        'last_name': value.lastName,
        'marital_status': MaritalStatusesToJSON(value.maritalStatus),
        'date_of_birth': value.dateOfBirth,
        'email': value.email,
        'phone': value.phone,
        'house_number': value.houseNumber,
        'street': value.street,
        'city': value.city,
        'postcode': value.postcode,
        'live_together': value.liveTogether,
        'personal_relation': value.personalRelation,
        'guardians': value.guardians,
    };
}


