/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ArticlesCollectionObject,
    ArticlesCollectionObjectFromJSON,
    ArticlesCollectionObjectFromJSONTyped,
    ArticlesCollectionObjectToJSON,
} from './';

/**
 * Article collection response object.
 * @export
 * @interface ArticleCollectionResponse
 */
export interface ArticleCollectionResponse {
    /**
     * 
     * @type {ArticlesCollectionObject}
     * @memberof ArticleCollectionResponse
     */
    data: ArticlesCollectionObject;
}

export function ArticleCollectionResponseFromJSON(json: any): ArticleCollectionResponse {
    return ArticleCollectionResponseFromJSONTyped(json, false);
}

export function ArticleCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleCollectionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ArticlesCollectionObjectFromJSON(json['data']),
    };
}

export function ArticleCollectionResponseToJSON(value?: ArticleCollectionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ArticlesCollectionObjectToJSON(value.data),
    };
}


