/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AssetTypes,
    AssetTypesFromJSON,
    AssetTypesFromJSONTyped,
    AssetTypesToJSON,
} from './';

/**
 * Asset object.
 * @export
 * @interface AssetObject
 */
export interface AssetObject {
    /**
     * 
     * @type {number}
     * @memberof AssetObject
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AssetObject
     */
    name: string;
    /**
     * 
     * @type {AssetTypes}
     * @memberof AssetObject
     */
    type: AssetTypes;
}

export function AssetObjectFromJSON(json: any): AssetObject {
    return AssetObjectFromJSONTyped(json, false);
}

export function AssetObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': AssetTypesFromJSON(json['type']),
    };
}

export function AssetObjectToJSON(value?: AssetObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': AssetTypesToJSON(value.type),
    };
}


