/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Attorneys decisions object.
 * @export
 * @enum {string}
 */
export enum AttorneysDecisions {
    JointlyAndSeverallySimpwillRecommends = 'Jointly and severally (Simpwill recommends)',
    Jointly = 'Jointly',
    JointlyForSomeDecisionsSeparatelyForOthers = 'Jointly for some decisions, separately for others'
}

export function AttorneysDecisionsFromJSON(json: any): AttorneysDecisions {
    return AttorneysDecisionsFromJSONTyped(json, false);
}

export function AttorneysDecisionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttorneysDecisions {
    return json as AttorneysDecisions;
}

export function AttorneysDecisionsToJSON(value?: AttorneysDecisions | null): any {
    return value as any;
}

