/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Beneficiaries object.
 * @export
 * @interface BeneficiariesObject
 */
export interface BeneficiariesObject {
    /**
     * 
     * @type {Array<number>}
     * @memberof BeneficiariesObject
     */
    actors: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof BeneficiariesObject
     */
    charities: Array<number>;
}

export function BeneficiariesObjectFromJSON(json: any): BeneficiariesObject {
    return BeneficiariesObjectFromJSONTyped(json, false);
}

export function BeneficiariesObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): BeneficiariesObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actors': json['actors'],
        'charities': json['charities'],
    };
}

export function BeneficiariesObjectToJSON(value?: BeneficiariesObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actors': value.actors,
        'charities': value.charities,
    };
}


