/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CharityObject,
    CharityObjectFromJSON,
    CharityObjectFromJSONTyped,
    CharityObjectToJSON,
} from './';

/**
 * Charity collection response object.
 * @export
 * @interface CharityCollectionResponse
 */
export interface CharityCollectionResponse {
    /**
     * 
     * @type {Array<CharityObject>}
     * @memberof CharityCollectionResponse
     */
    data: Array<CharityObject>;
}

export function CharityCollectionResponseFromJSON(json: any): CharityCollectionResponse {
    return CharityCollectionResponseFromJSONTyped(json, false);
}

export function CharityCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharityCollectionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CharityObjectFromJSON)),
    };
}

export function CharityCollectionResponseToJSON(value?: CharityCollectionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(CharityObjectToJSON)),
    };
}


