/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Charity object.
 * @export
 * @interface CharityObject
 */
export interface CharityObject {
    /**
     * 
     * @type {number}
     * @memberof CharityObject
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CharityObject
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CharityObject
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof CharityObject
     */
    photo: string;
    /**
     * 
     * @type {string}
     * @memberof CharityObject
     */
    description: string;
}

export function CharityObjectFromJSON(json: any): CharityObject {
    return CharityObjectFromJSONTyped(json, false);
}

export function CharityObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharityObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'number': json['number'],
        'photo': json['photo'],
        'description': json['description'],
    };
}

export function CharityObjectToJSON(value?: CharityObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'number': value.number,
        'photo': value.photo,
        'description': value.description,
    };
}


