/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Coupon request object
 * @export
 * @interface CouponRequest
 */
export interface CouponRequest {
    /**
     * 
     * @type {string}
     * @memberof CouponRequest
     */
    coupon: string;
}

export function CouponRequestFromJSON(json: any): CouponRequest {
    return CouponRequestFromJSONTyped(json, false);
}

export function CouponRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'coupon': json['coupon'],
    };
}

export function CouponRequestToJSON(value?: CouponRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'coupon': value.coupon,
    };
}


