/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Discount object.
 * @export
 * @interface DiscountObject
 */
export interface DiscountObject {
    /**
     * 
     * @type {number}
     * @memberof DiscountObject
     */
    discount: number;
}

export function DiscountObjectFromJSON(json: any): DiscountObject {
    return DiscountObjectFromJSONTyped(json, false);
}

export function DiscountObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discount': json['discount'],
    };
}

export function DiscountObjectToJSON(value?: DiscountObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discount': value.discount,
    };
}


