/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Donor and appliers object.
 * @export
 * @enum {string}
 */
export enum DonorAndAppliers {
    Donor = 'donor',
    Attorneys = 'attorneys'
}

export function DonorAndAppliersFromJSON(json: any): DonorAndAppliers {
    return DonorAndAppliersFromJSONTyped(json, false);
}

export function DonorAndAppliersFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonorAndAppliers {
    return json as DonorAndAppliers;
}

export function DonorAndAppliersToJSON(value?: DonorAndAppliers | null): any {
    return value as any;
}

