/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Error object.
 * @export
 * @interface ErrorsObject
 */
export interface ErrorsObject {
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorsObject
     */
    errors: Array<string>;
}

export function ErrorsObjectFromJSON(json: any): ErrorsObject {
    return ErrorsObjectFromJSONTyped(json, false);
}

export function ErrorsObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorsObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': json['errors'],
    };
}

export function ErrorsObjectToJSON(value?: ErrorsObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors,
    };
}


