/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Guide preview object.
 * @export
 * @interface GuidePreviewObject
 */
export interface GuidePreviewObject {
    /**
     * 
     * @type {number}
     * @memberof GuidePreviewObject
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GuidePreviewObject
     */
    title: string;
}

export function GuidePreviewObjectFromJSON(json: any): GuidePreviewObject {
    return GuidePreviewObjectFromJSONTyped(json, false);
}

export function GuidePreviewObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuidePreviewObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
    };
}

export function GuidePreviewObjectToJSON(value?: GuidePreviewObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
    };
}


