/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Invite partner request object
 * @export
 * @interface InvitePartnerRequest
 */
export interface InvitePartnerRequest {
    /**
     * 
     * @type {string}
     * @memberof InvitePartnerRequest
     */
    email: string;
}

export function InvitePartnerRequestFromJSON(json: any): InvitePartnerRequest {
    return InvitePartnerRequestFromJSONTyped(json, false);
}

export function InvitePartnerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvitePartnerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function InvitePartnerRequestToJSON(value?: InvitePartnerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}


