/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LpaObject,
    LpaObjectFromJSON,
    LpaObjectFromJSONTyped,
    LpaObjectToJSON,
} from './';

/**
 * Lpa response.
 * @export
 * @interface LpaResponse
 */
export interface LpaResponse {
    /**
     * 
     * @type {LpaObject}
     * @memberof LpaResponse
     */
    data: LpaObject;
}

export function LpaResponseFromJSON(json: any): LpaResponse {
    return LpaResponseFromJSONTyped(json, false);
}

export function LpaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LpaResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': LpaObjectFromJSON(json['data']),
    };
}

export function LpaResponseToJSON(value?: LpaResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': LpaObjectToJSON(value.data),
    };
}


