/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PetObject,
    PetObjectFromJSON,
    PetObjectFromJSONTyped,
    PetObjectToJSON,
} from './';

/**
 * Pet response object.
 * @export
 * @interface PetResponse
 */
export interface PetResponse {
    /**
     * 
     * @type {PetObject}
     * @memberof PetResponse
     */
    data: PetObject;
}

export function PetResponseFromJSON(json: any): PetResponse {
    return PetResponseFromJSONTyped(json, false);
}

export function PetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': PetObjectFromJSON(json['data']),
    };
}

export function PetResponseToJSON(value?: PetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': PetObjectToJSON(value.data),
    };
}


