/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Preference request object for create.
 * @export
 * @interface PreferenceCreateRequest
 */
export interface PreferenceCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof PreferenceCreateRequest
     */
    documentId: number;
    /**
     * 
     * @type {string}
     * @memberof PreferenceCreateRequest
     */
    name: string;
}

export function PreferenceCreateRequestFromJSON(json: any): PreferenceCreateRequest {
    return PreferenceCreateRequestFromJSONTyped(json, false);
}

export function PreferenceCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferenceCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': json['document_id'],
        'name': json['name'],
    };
}

export function PreferenceCreateRequestToJSON(value?: PreferenceCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'document_id': value.documentId,
        'name': value.name,
    };
}


