/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PreferenceObject,
    PreferenceObjectFromJSON,
    PreferenceObjectFromJSONTyped,
    PreferenceObjectToJSON,
} from './';

/**
 * Preference response.
 * @export
 * @interface PreferenceResponse
 */
export interface PreferenceResponse {
    /**
     * 
     * @type {PreferenceObject}
     * @memberof PreferenceResponse
     */
    data: PreferenceObject;
}

export function PreferenceResponseFromJSON(json: any): PreferenceResponse {
    return PreferenceResponseFromJSONTyped(json, false);
}

export function PreferenceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreferenceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': PreferenceObjectFromJSON(json['data']),
    };
}

export function PreferenceResponseToJSON(value?: PreferenceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': PreferenceObjectToJSON(value.data),
    };
}


