/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Receiver request object
 * @export
 * @interface ReceiverRequestObject
 */
export interface ReceiverRequestObject {
    /**
     * 
     * @type {boolean}
     * @memberof ReceiverRequestObject
     */
    donor?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ReceiverRequestObject
     */
    actor?: number;
}

export function ReceiverRequestObjectFromJSON(json: any): ReceiverRequestObject {
    return ReceiverRequestObjectFromJSONTyped(json, false);
}

export function ReceiverRequestObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiverRequestObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'donor': !exists(json, 'donor') ? undefined : json['donor'],
        'actor': !exists(json, 'actor') ? undefined : json['actor'],
    };
}

export function ReceiverRequestObjectToJSON(value?: ReceiverRequestObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'donor': value.donor,
        'actor': value.actor,
    };
}


