/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Tag object.
 * @export
 * @interface TagObject
 */
export interface TagObject {
    /**
     * 
     * @type {number}
     * @memberof TagObject
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TagObject
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TagObject
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof TagObject
     */
    color: string;
}

export function TagObjectFromJSON(json: any): TagObject {
    return TagObjectFromJSONTyped(json, false);
}

export function TagObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'color': json['color'],
    };
}

export function TagObjectToJSON(value?: TagObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'slug': value.slug,
        'color': value.color,
    };
}


