/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Google server code to get user data.
 * @export
 * @interface UserAuthenticateWithGoogle
 */
export interface UserAuthenticateWithGoogle {
    /**
     * 
     * @type {string}
     * @memberof UserAuthenticateWithGoogle
     */
    googleServerAuthCode: string;
    /**
     * 
     * @type {string}
     * @memberof UserAuthenticateWithGoogle
     */
    fullName: string;
}

export function UserAuthenticateWithGoogleFromJSON(json: any): UserAuthenticateWithGoogle {
    return UserAuthenticateWithGoogleFromJSONTyped(json, false);
}

export function UserAuthenticateWithGoogleFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAuthenticateWithGoogle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'googleServerAuthCode': json['google_server_auth_code'],
        'fullName': json['full_name'],
    };
}

export function UserAuthenticateWithGoogleToJSON(value?: UserAuthenticateWithGoogle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'google_server_auth_code': value.googleServerAuthCode,
        'full_name': value.fullName,
    };
}


