/* tslint:disable */
/* eslint-disable */
/**
 * Simpwill API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The request data to login the user.
 * @export
 * @interface UserDataForLogin
 */
export interface UserDataForLogin {
    /**
     * 
     * @type {string}
     * @memberof UserDataForLogin
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDataForLogin
     */
    password: string;
}

export function UserDataForLoginFromJSON(json: any): UserDataForLogin {
    return UserDataForLoginFromJSONTyped(json, false);
}

export function UserDataForLoginFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDataForLogin {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function UserDataForLoginToJSON(value?: UserDataForLogin | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}


